# Generated by Django 6.0.6 on 2026-07-08 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Member',
        ),
    ]
