# Generated by Django 6.0.6 on 2026-07-08 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_rename_model_member'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Driver',
        ),
    ]
