# Generated by Django 6.0.6 on 2026-07-08 08:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_rename_member_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='F1Team',
            field=models.CharField(default='F1', max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='Nationality',
            field=models.CharField(default='World-Country', max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='Points',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='lastRace_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
